// purdueMajors.mjs
//
// Every undergraduate degree program Purdue admits into, transcribed from the
// official University Catalog "Undergraduate Programs List". This is the pick
// list behind the degree planner's major selector: a few of these majors also
// have curated requirement data in degreePrograms.mjs, the rest are selectable
// so a student can record their major even before we map its plan of study.
//
// Source: https://purdue.catalog.acalog.com/content.php?catoid=14&navoid=16929
//
// Minors and certificates are deliberately excluded - this is a major picker.
// Catalog names are normalized to a "Program: Concentration" shape (the catalog
// mixes "/", ":" and a trailing "Concentration"/"Track") so the list sorts and
// searches predictably.
//
// `id` is derived from `name` and is persisted (users.major, localStorage), so
// renaming an entry changes its id - add an explicit `id` instead when a name
// has to change, and when two programs share a name across degrees.

/** "Women's, Gender & Sexuality Studies" -> "womens-gender-sexuality-studies". */
export function majorId(name) {
  return String(name)
    .toLowerCase()
    .replace(/['\u2019]/g, '')
    .replace(/&/g, ' and ')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

// Degree abbreviation -> full name, for tooltips and grouping.
export const DEGREE_LABELS = {
  AAS: 'Associate in Applied Science',
  AS: 'Associate of Science',
  BA: 'Bachelor of Arts',
  BFA: 'Bachelor of Fine Arts',
  BS: 'Bachelor of Science',
  BSAAE: 'BS in Aeronautical and Astronautical Engineering',
  BSAGE: 'BS in Agricultural Engineering',
  BSBE: 'BS in Biological Engineering',
  BSBME: 'BS in Biomedical Engineering',
  BSCE: 'BS in Civil Engineering',
  BSCH: 'BS in Chemistry',
  BSCHE: 'BS in Chemical Engineering',
  BSCMPE: 'BS in Computer Engineering',
  BSCNE: 'BS in Construction Engineering',
  BSE: 'BS in Engineering',
  BSEE: 'BS in Electrical Engineering',
  BSEEE: 'BS in Environmental and Ecological Engineering',
  BSFOR: 'BS in Forestry',
  BSIE: 'BS in Industrial Engineering',
  BSLA: 'BS in Landscape Architecture',
  BSME: 'BS in Mechanical Engineering',
  BSMSE: 'BS in Materials Science and Engineering',
  BSN: 'BS in Nursing',
  BSNE: 'BS in Nuclear Engineering',
  BSVN: 'BS in Veterinary Nursing',
}

// name + degree, in catalog order. Explicit ids only where two programs would
// otherwise collide (the same name offered under two degrees).
const CATALOG = [
  // Associate in Applied Science
  { name: 'Veterinary Nurse', degree: 'AAS' },
  { name: 'Veterinary Nurse Distance Learning', degree: 'AAS' },

  // Associate of Science
  {
    name: 'Polytechnic Statewide Mechanical Engineering Technology',
    degree: 'AS',
    id: 'polytechnic-statewide-mechanical-engineering-technology-as',
  },

  // Bachelor of Arts
  { name: 'African American Studies', degree: 'BA' },
  { name: 'American Studies', degree: 'BA' },
  { name: 'Anthropology', degree: 'BA' },
  { name: 'Anthropology Honors', degree: 'BA' },
  { name: 'Art History', degree: 'BA' },
  { name: 'Asian Studies', degree: 'BA' },
  { name: 'Chinese Studies', degree: 'BA' },
  { name: 'Classical Studies: Classical Languages', degree: 'BA' },
  { name: 'Classical Studies: Literature & Culture', degree: 'BA' },
  { name: 'Classical Studies: Material Culture & History', degree: 'BA' },
  { name: 'Communication: Business Communication', degree: 'BA' },
  { name: 'Communication: Communication of Science and Technology', degree: 'BA' },
  { name: 'Communication: General Communication', degree: 'BA' },
  { name: 'Communication: Health Communication', degree: 'BA' },
  { name: 'Communication: Interpersonal Communication', degree: 'BA' },
  { name: 'Communication: Media and Mass Communication', degree: 'BA' },
  { name: 'Communication: Political and Civic Communication', degree: 'BA' },
  { name: 'Communication: Public Relations and Strategic Communication', degree: 'BA' },
  { name: 'Comparative Literature', degree: 'BA' },
  { name: 'Creative Writing', degree: 'BA' },
  { name: 'Digital Criminology', degree: 'BA' },
  { name: 'Economics', degree: 'BA', id: 'economics-ba' },
  { name: 'Economics Honors', degree: 'BA', id: 'economics-honors-ba' },
  { name: 'Elementary Education', degree: 'BA' },
  { name: 'English: English Education', degree: 'BA' },
  { name: 'English: English Literature', degree: 'BA' },
  { name: 'English: Global Context', degree: 'BA' },
  { name: 'Film & Video Production', degree: 'BA' },
  { name: 'Film & Video Studies', degree: 'BA' },
  { name: 'French', degree: 'BA' },
  { name: 'General Education: Curriculum and Instruction (non-licensure)', degree: 'BA' },
  { name: 'General Education: Educational Studies (non-licensure)', degree: 'BA' },
  { name: 'German', degree: 'BA' },
  { name: 'Global Studies', degree: 'BA' },
  { name: 'History', degree: 'BA' },
  { name: 'History Honors', degree: 'BA' },
  { name: 'Italian Studies', degree: 'BA' },
  { name: 'Japanese', degree: 'BA' },
  { name: 'Jewish Studies', degree: 'BA' },
  { name: 'Law and Society', degree: 'BA' },
  { name: 'Linguistics', degree: 'BA' },
  { name: 'Music', degree: 'BA' },
  { name: 'Philosophy', degree: 'BA' },
  { name: 'Political Science', degree: 'BA' },
  { name: 'Professional Writing', degree: 'BA' },
  { name: 'Religious Studies', degree: 'BA' },
  { name: 'Russian', degree: 'BA' },
  { name: 'Social Studies Education', degree: 'BA' },
  { name: 'Sociology', degree: 'BA' },
  { name: 'Sound for the Performing Arts', degree: 'BA' },
  { name: 'Spanish', degree: 'BA' },
  { name: 'Special Education / Elementary Education', degree: 'BA' },
  { name: 'Special Education: Mild & Intense Intervention 5-12', degree: 'BA' },
  { name: 'Special Education: Mild & Intense Intervention K-6', degree: 'BA' },
  { name: 'Studio Arts and Technology', degree: 'BA' },
  { name: 'Theatre', degree: 'BA' },
  { name: 'Visual Arts Design Education', degree: 'BA' },
  { name: 'Visual Arts Education', degree: 'BA' },
  { name: 'Women’s, Gender & Sexuality Studies', degree: 'BA' },

  // Bachelor of Fine Arts
  { name: 'Industrial Design Professional Program', degree: 'BFA' },
  { name: 'Integrated Studio Arts', degree: 'BFA' },
  { name: 'Interior Design Professional Program', degree: 'BFA' },
  { name: 'Visual Communication Design', degree: 'BFA' },

  // Bachelor of Science
  { name: 'Accounting', degree: 'BS' },
  { name: 'Actuarial Science', degree: 'BS' },
  { name: 'Actuarial Science Honors', degree: 'BS' },
  { name: 'Aeronautical Engineering Technology', degree: 'BS' },
  { name: 'Aerospace Financial Analysis', degree: 'BS' },
  { name: 'Agribusiness: Agribusiness Management', degree: 'BS' },
  { name: 'Agribusiness: Agricultural Finance', degree: 'BS' },
  { name: 'Agribusiness: Agricultural Marketing', degree: 'BS' },
  { name: 'Agribusiness: Commodity Marketing', degree: 'BS' },
  { name: 'Agribusiness: Food Marketing', degree: 'BS' },
  { name: 'Agricultural Communication', degree: 'BS' },
  { name: 'Agricultural Economics: Applied Agricultural Economics', degree: 'BS' },
  { name: 'Agricultural Economics: Commodity Marketing', degree: 'BS' },
  { name: 'Agricultural Economics: Quantitative Analysis', degree: 'BS' },
  { name: 'Agricultural Education', degree: 'BS' },
  { name: 'Agricultural Systems Management', degree: 'BS' },
  { name: 'Agricultural Systems Management: AgroSecurity', degree: 'BS' },
  { name: 'Agricultural Systems Management: Data and Information Systems', degree: 'BS' },
  { name: 'Agricultural Systems Management: Leadership and Management', degree: 'BS' },
  { name: 'Agronomy: Agronomic Business and Marketing', degree: 'BS' },
  { name: 'Agronomy: Crop and Soil Management', degree: 'BS' },
  { name: 'Agronomy: International Agronomy', degree: 'BS' },
  { name: 'Airline Management and Operations', degree: 'BS' },
  { name: 'Airport Management and Operations', degree: 'BS' },
  { name: 'Animal Sciences: Animal Agribusiness', degree: 'BS' },
  { name: 'Animal Sciences: Animal Production and Industry', degree: 'BS' },
  { name: 'Animal Sciences: Behavior / Well-Being', degree: 'BS' },
  { name: 'Animal Sciences: Biosciences', degree: 'BS' },
  { name: 'Animal Sciences: Pre-Veterinary Medicine', degree: 'BS' },
  { name: 'Animation', degree: 'BS' },
  { name: 'Applied Mathematics', degree: 'BS' },
  { name: 'Applied Meteorology and Climatology', degree: 'BS' },
  { name: 'Applied Physics', degree: 'BS' },
  { name: 'Applied Physics Honors', degree: 'BS' },
  { name: 'Applied Statistics', degree: 'BS' },
  { name: 'Aquatic Sciences: Fisheries', degree: 'BS' },
  { name: 'Aquatic Sciences: Marine and Freshwater Biology', degree: 'BS' },
  { name: 'Atmospheric Science', degree: 'BS' },
  { name: 'Audio Engineering Technology', degree: 'BS' },
  { name: 'Automation and Systems Integration Engineering Technology', degree: 'BS' },
  { name: 'Aviation Management', degree: 'BS' },
  { name: 'Biochemistry', degree: 'BS' },
  { name: 'Biochemistry: Pre-Med', degree: 'BS' },
  { name: 'Biochemistry: Pre-Vet', degree: 'BS' },
  { name: 'Biology', degree: 'BS' },
  { name: 'Biomedical Health Sciences: Interdisciplinary Health Science', degree: 'BS' },
  { name: 'Biomedical Health Sciences: Pre-Dentistry', degree: 'BS' },
  { name: 'Biomedical Health Sciences: Pre-Medicine', degree: 'BS' },
  { name: 'Biomedical Health Sciences: Pre-Optometry', degree: 'BS' },
  { name: 'Biomedical Health Sciences: Pre-Physician Assistant', degree: 'BS' },
  { name: 'Brain and Behavioral Sciences', degree: 'BS' },
  { name: 'Building Information Modeling', degree: 'BS' },
  { name: 'Business Analytics & Information Management', degree: 'BS' },
  { name: 'Cell, Molecular, and Developmental Biology', degree: 'BS' },
  { name: 'Chemical Biology & Biochemistry', degree: 'BS' },
  { name: 'Chemistry', degree: 'BS' },
  { name: 'Computer and Information Technology', degree: 'BS' },
  { name: 'Computer Engineering Technology', degree: 'BS' },
  // Curated requirements live in degreePrograms.mjs (id: computer-science).
  { name: 'Computer Science', degree: 'BS' },
  { name: 'Computer Science Honors', degree: 'BS' },
  { name: 'Computing Infrastructure and Network Engineering Technology', degree: 'BS' },
  { name: 'Construction Management', degree: 'BS' },
  { name: 'Coordinated Program in Dietetics', degree: 'BS' },
  { name: 'Crop Science', degree: 'BS' },
  { name: 'Cybersecurity', degree: 'BS' },
  { name: 'Data Analytics, Technologies, and Applications', degree: 'BS' },
  // Curated requirements live in degreePrograms.mjs (id: data-science).
  { name: 'Data Science', degree: 'BS' },
  { name: 'Data Science (Mathematics)', degree: 'BS' },
  { name: 'Data Science (Statistics)', degree: 'BS' },
  { name: 'Data Visualization', degree: 'BS' },
  { name: 'Design and Construction Integration', degree: 'BS' },
  { name: 'Developmental and Family Science', degree: 'BS' },
  { name: 'Dietetics / Nutrition, Fitness and Health', degree: 'BS' },
  { name: 'Early Childhood Education and Exceptional Needs', degree: 'BS' },
  { name: 'Ecology, Evolution, and Environmental Biology', degree: 'BS' },
  { name: 'Economics', degree: 'BS' },
  { name: 'Economics Honors', degree: 'BS' },
  { name: 'Electrical Engineering Technology', degree: 'BS' },
  { name: 'Energy Engineering Technology', degree: 'BS' },
  { name: 'Environmental Geoscience', degree: 'BS' },
  { name: 'Family and Consumer Sciences Education', degree: 'BS' },
  { name: 'Farm Management', degree: 'BS' },
  { name: 'Finance', degree: 'BS' },
  { name: 'Financial Counseling and Planning', degree: 'BS' },
  { name: 'Food Science', degree: 'BS' },
  { name: 'Game Development and Design', degree: 'BS' },
  { name: 'General Management', degree: 'BS' },
  { name: 'Genetics', degree: 'BS' },
  { name: 'Geology and Geophysics', degree: 'BS' },
  { name: 'Health and Disease', degree: 'BS' },
  { name: 'Horticulture: Horticultural Production and Marketing', degree: 'BS' },
  { name: 'Horticulture: Landscape Contracting and Management', degree: 'BS' },
  { name: 'Horticulture: Landscape Design', degree: 'BS' },
  { name: 'Horticulture: Landscape Enterprise Management', degree: 'BS' },
  { name: 'Horticulture: Plant Science', degree: 'BS' },
  { name: 'Horticulture: Public Horticulture', degree: 'BS' },
  { name: 'Hospitality and Tourism Management', degree: 'BS' },
  { name: 'Human Resource Development', degree: 'BS' },
  { name: 'Human Services', degree: 'BS' },
  { name: 'Industrial Engineering Technology', degree: 'BS' },
  { name: 'Insect Biology', degree: 'BS' },
  { name: 'Insect Biology: Forensic Entomology', degree: 'BS' },
  { name: 'Integrated Business & Engineering', degree: 'BS' },
  { name: 'Interdisciplinary Engineering Studies: Engineering Science Studies', degree: 'BS' },
  { name: 'Interdisciplinary Engineering Studies: Pre-Med', degree: 'BS' },
  { name: 'Interdisciplinary Science (Biology)', degree: 'BS' },
  { name: 'Interdisciplinary Science (Chemistry)', degree: 'BS' },
  { name: 'Interdisciplinary Science (Computer Science)', degree: 'BS' },
  { name: 'Interdisciplinary Science (Earth, Atmospheric, and Planetary Sciences)', degree: 'BS' },
  { name: 'Interdisciplinary Science (Mathematics)', degree: 'BS' },
  { name: 'Interdisciplinary Science (Physics)', degree: 'BS' },
  { name: 'Interdisciplinary Science (Statistics)', degree: 'BS' },
  { name: 'Kinesiology', degree: 'BS' },
  { name: 'Marketing', degree: 'BS' },
  { name: 'Mathematics', degree: 'BS' },
  { name: 'Mathematics / Business', degree: 'BS' },
  { name: 'Mathematics / Computer Science', degree: 'BS' },
  { name: 'Mathematics / Statistics', degree: 'BS' },
  { name: 'Mathematics Education', degree: 'BS' },
  { name: 'Mathematics Honors', degree: 'BS' },
  { name: 'Mechanical Engineering Technology', degree: 'BS' },
  { name: 'Mechatronics Engineering Technology', degree: 'BS' },
  { name: 'Medical Laboratory Sciences', degree: 'BS' },
  { name: 'Microbiology', degree: 'BS' },
  { name: 'Microbiology Honors', degree: 'BS' },
  { name: 'Natural Resources and Environmental Science: Climate and Energy Solutions', degree: 'BS' },
  {
    name: 'Natural Resources and Environmental Science: Emerging Environmental Challenges',
    degree: 'BS',
  },
  { name: 'Natural Resources and Environmental Science: Environmental Policy and Analysis', degree: 'BS' },
  {
    name: 'Natural Resources and Environmental Science: Environmental Quality and Restoration',
    degree: 'BS',
  },
  { name: 'Natural Resources and Environmental Science: Sustainability Science', degree: 'BS' },
  { name: 'Natural Resources and Environmental Science: Watershed Management', degree: 'BS' },
  { name: 'Neurobiology and Physiology', degree: 'BS' },
  { name: 'Nutrition and Dietetics', degree: 'BS' },
  { name: 'Nutrition Science', degree: 'BS' },
  { name: 'Nutrition, Fitness, and Health', degree: 'BS' },
  { name: 'Occupational and Environmental Health Sciences', degree: 'BS' },
  { name: 'Organizational Leadership', degree: 'BS' },
  { name: 'Pharmaceutical Sciences', degree: 'BS' },
  { name: 'Physics', degree: 'BS' },
  { name: 'Physics Honors', degree: 'BS' },
  { name: 'Planetary Sciences', degree: 'BS' },
  { name: 'Plant Genetics, Breeding, and Biotechnology', degree: 'BS' },
  { name: 'Plant Science', degree: 'BS' },
  { name: 'Polytechnic Statewide Aeronautical Technology', degree: 'BS' },
  { name: 'Polytechnic Statewide Animation', degree: 'BS' },
  { name: 'Polytechnic Statewide Computer and Information Technology', degree: 'BS' },
  { name: 'Polytechnic Statewide Computer Graphics Technology', degree: 'BS' },
  { name: 'Polytechnic Statewide Cybersecurity', degree: 'BS' },
  { name: 'Polytechnic Statewide Electrical Engineering Technology', degree: 'BS' },
  { name: 'Polytechnic Statewide Engineering Technology', degree: 'BS' },
  { name: 'Polytechnic Statewide Game Development and Design', degree: 'BS' },
  { name: 'Polytechnic Statewide Industrial Engineering Technology', degree: 'BS' },
  { name: 'Polytechnic Statewide Mechanical Engineering Technology', degree: 'BS' },
  { name: 'Polytechnic Statewide Mechatronics Engineering Technology', degree: 'BS' },
  { name: 'Polytechnic Statewide Multidisciplinary Technology', degree: 'BS' },
  { name: 'Polytechnic Statewide Robotics Engineering Technology', degree: 'BS' },
  { name: 'Polytechnic Statewide Web Programming & Design', degree: 'BS' },
  { name: 'Professional Flight Technology', degree: 'BS' },
  { name: 'Psychological Sciences', degree: 'BS' },
  { name: 'Public Health: Behavioral Social Sciences', degree: 'BS' },
  { name: 'Public Health: Biostatistics / Communications & Informatics / Systems Thinking', degree: 'BS' },
  { name: 'Public Health: Environmental Health / Epidemiology / Public Health Biology', degree: 'BS' },
  { name: 'Public Health: Global Health', degree: 'BS' },
  { name: 'Public Health: Health Policy & Management', degree: 'BS' },
  { name: 'Public Health: Interdisciplinary', degree: 'BS' },
  { name: 'Radiological Health Sciences: Health Physics', degree: 'BS' },
  { name: 'Radiological Health Sciences: Pre-Medical Physics', degree: 'BS' },
  { name: 'Retail Management', degree: 'BS' },
  { name: 'Robotics Engineering Technology', degree: 'BS' },
  { name: 'Sales and Marketing', degree: 'BS' },
  { name: 'Science Education: Biology', degree: 'BS' },
  { name: 'Science Education: Chemistry', degree: 'BS' },
  { name: 'Science Education: Earth Space Science', degree: 'BS' },
  { name: 'Science Education: Physics', degree: 'BS' },
  { name: 'Selling and Sales Management', degree: 'BS' },
  { name: 'Smart Manufacturing Industrial Informatics', degree: 'BS' },
  { name: 'Soil and Water Sciences', degree: 'BS' },
  { name: 'Speech, Language, and Hearing Sciences', degree: 'BS' },
  { name: 'Statistics: Math Emphasis', degree: 'BS' },
  { name: 'Statistics Honors', degree: 'BS' },
  { name: 'Supply Chain & Operations Management', degree: 'BS' },
  { name: 'Supply Chain & Sales Engineering Technology', degree: 'BS' },
  { name: 'Supply Chain, Information and Analytics', degree: 'BS' },
  { name: 'Sustainable Food and Farming Systems', degree: 'BS' },
  { name: 'Systems Analysis and Design', degree: 'BS' },
  { name: 'Technology Education', degree: 'BS' },
  { name: 'Turf Management and Science', degree: 'BS' },
  { name: 'Unmanned Aerial Systems', degree: 'BS' },
  { name: 'UX Design', degree: 'BS' },
  { name: 'Virtual Product Integration', degree: 'BS' },
  { name: 'Visual Effects Compositing', degree: 'BS' },
  { name: 'Web Programming & Design', degree: 'BS' },
  { name: 'Wildlife', degree: 'BS' },

  // Named engineering / professional bachelor's degrees
  { name: 'Aeronautical and Astronautical Engineering', degree: 'BSAAE' },
  { name: 'Agricultural Engineering', degree: 'BSAGE' },
  { name: 'Environmental and Natural Resources Engineering', degree: 'BSAGE' },
  { name: 'Biological Engineering', degree: 'BSBE' },
  { name: 'Biological Engineering: BioEnvironmental Engineering', degree: 'BSBE' },
  { name: 'Biological Engineering: Cellular and Biomolecular Engineering', degree: 'BSBE' },
  { name: 'Biological Engineering: Food and Biological Process Engineering', degree: 'BSBE' },
  { name: 'Biological Engineering: Pharmaceutical Process Engineering', degree: 'BSBE' },
  { name: 'Biomedical Engineering', degree: 'BSBME' },
  { name: 'Chemical Engineering', degree: 'BSCHE' },
  { name: 'Biochemistry (Chemistry)', degree: 'BSCH' },
  { name: 'Chemistry (ACS)', degree: 'BSCH' },
  { name: 'Civil Engineering', degree: 'BSCE' },
  { name: 'Computer Engineering', degree: 'BSCMPE' },
  { name: 'Construction Engineering', degree: 'BSCNE' },
  { name: 'Multidisciplinary Engineering: Acoustical Engineering', degree: 'BSE' },
  { name: 'Multidisciplinary Engineering: Educational Engineering', degree: 'BSE' },
  { name: 'Multidisciplinary Engineering: Engineering Management', degree: 'BSE' },
  { name: 'Multidisciplinary Engineering: General Engineering', degree: 'BSE' },
  { name: 'Multidisciplinary Engineering: Humanitarian Engineering', degree: 'BSE' },
  { name: 'Multidisciplinary Engineering: Lighting', degree: 'BSE' },
  { name: 'Multidisciplinary Engineering: Nano Engineering', degree: 'BSE' },
  { name: 'Multidisciplinary Engineering: Theatre Engineering', degree: 'BSE' },
  { name: 'Multidisciplinary Engineering: Visual Design Engineering', degree: 'BSE' },
  // Curated requirements live in degreePrograms.mjs (id: electrical-engineering).
  { name: 'Electrical Engineering', degree: 'BSEE' },
  { name: 'Environmental and Ecological Engineering', degree: 'BSEEE' },
  { name: 'Forestry: Forest Management', degree: 'BSFOR' },
  { name: 'Forestry: Forest Science', degree: 'BSFOR' },
  { name: 'Forestry: Sustainable Biomaterials', degree: 'BSFOR' },
  { name: 'Forestry: Urban Forestry', degree: 'BSFOR' },
  { name: 'Industrial Engineering', degree: 'BSIE' },
  { name: 'Landscape Architecture', degree: 'BSLA' },
  { name: 'Mechanical Engineering', degree: 'BSME' },
  { name: 'Materials Engineering', degree: 'BSMSE' },
  { name: 'Accelerated Nursing', degree: 'BSN' },
  { name: 'Nursing', degree: 'BSN' },
  { name: 'Nuclear Engineering', degree: 'BSNE' },
  { name: 'Veterinary Nurse Completion', degree: 'BSVN' },
  { name: 'Veterinary Nursing', degree: 'BSVN' },
]

/** Every Purdue undergraduate major as { id, name, degree }, sorted by name. */
export const PURDUE_MAJORS = CATALOG.map(({ id, name, degree }) => ({
  id: id || majorId(name),
  name,
  degree,
})).sort((a, b) => a.name.localeCompare(b.name))
